package cards

type Card struct {
	Object          string        `json:"object"`
	Id              string        `json:"id"`
	OracleId        string        `json:"oracle_id"`
	MultiverseIds   []int         `json:"multiverse_ids"`
	MtgoId          int           `json:"mtgo_id"`
	TcgplayerId     int           `json:"tcgplayer_id"`
	CardmarketId    int           `json:"cardmarket_id"`
	Name            string        `json:"name"`
	Lang            string        `json:"lang"`
	ReleasedAt      string        `json:"released_at"`
	Uri             string        `json:"uri"`
	ScryfallUri     string        `json:"scryfall_uri"`
	Layout          string        `json:"layout"`
	HighresImage    bool          `json:"highres_image"`
	ImageStatus     string        `json:"image_status"`
	ImageUris       ImageUris     `json:"image_uris"`
	ManaCost        string        `json:"mana_cost"`
	Cmc             float64       `json:"cmc"`
	TypeLine        string        `json:"type_line"`
	OracleText      string        `json:"oracle_text"`
	Power           string        `json:"power"`
	Toughness       string        `json:"toughness"`
	Colors          []string      `json:"colors"`
	ColorIndicator  []string      `json:"color_indicator"`
	ColorIdentity   []string      `json:"color_identity"`
	Keywords        []interface{} `json:"keywords"`
	AllParts        []AllParts    `json:"all_parts"`
	Legalities      Legalitites   `json:"legalities"`
	Games           []string      `json:"games"`
	Reserved        bool          `json:"reserved"`
	Foil            bool          `json:"foil"`
	Nonfoil         bool          `json:"nonfoil"`
	Finishes        []string      `json:"finishes"`
	Oversized       bool          `json:"oversized"`
	Promo           bool          `json:"promo"`
	Reprint         bool          `json:"reprint"`
	Variation       bool          `json:"variation"`
	SetId           string        `json:"set_id"`
	Set             string        `json:"set"`
	SetName         string        `json:"set_name"`
	SetType         string        `json:"set_type"`
	SetUri          string        `json:"set_uri"`
	SetSearchUri    string        `json:"set_search_uri"`
	ScryfallSetUri  string        `json:"scryfall_set_uri"`
	RulingsUri      string        `json:"rulings_uri"`
	PrintsSearchUri string        `json:"prints_search_uri"`
	CollectorNumber string        `json:"collector_number"`
	Digital         bool          `json:"digital"`
	Rarity          string        `json:"rarity"`
	CardBackId      string        `json:"card_back_id"`
	Artist          string        `json:"artist"`
	ArtistIds       []string      `json:"artist_ids"`
	IllustrationId  string        `json:"illustration_id"`
	BorderColor     string        `json:"border_color"`
	Frame           string        `json:"frame"`
	FrameEffects    []string      `json:"frame_effects"`
	SecurityStamp   string        `json:"security_stamp"`
	FullArt         bool          `json:"full_art"`
	Textless        bool          `json:"textless"`
	Booster         bool          `json:"booster"`
	StorySpotlight  bool          `json:"story_spotlight"`
	EdhrecRank      int           `json:"edhrec_rank"`
	Preview         Preview       `json:"preview"`
	Prices          Prices        `json:"prices"`
	RelatedUris     RelatedUris   `json:"related_uris"`
	PurchaseUris    PurchaseUris  `json:"purchase_uris"`
}
